# Generated by Django 3.1.7 on 2021-03-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_auto_20210329_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='question',
            field=models.ManyToManyField(blank=True, to='judge.Question'),
        ),
    ]
